services:
  jekyll:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace
      - jekyll_cache:/workspace/.jekyll-cache # Use a named volume for the cache
    ports:
      - "4000:4000"
    environment:
      JEKYLL_ENV: development
    command: bundle exec jekyll serve --host=0.0.0.0

volumes:
  jekyll_cache:
