services:
  jekyll:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace
      - bundle_cache:/usr/local/bundle
    ports:
      - "4000:4000"
    environment:
      JEKYLL_ENV: development
    command: bundle exec jekyll serve --host=0.0.0.0

volumes:
  bundle_cache:
